#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob nocaseglob

/usr/bin/curl -fsSLo PortIndex "https://ftp.fau.de/macports/release/ports/PortIndex_darwin_20_i386/PortIndex"
/usr/bin/gzip PortIndex

exit 0