#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob nocaseglob

# path to self and parent dir
SCRIPT=$(realpath $0)
SCRIPTPATH=$(dirname $SCRIPT)

git -C /opt/mports/macports-base pull --rebase=false
cd /opt/mports/macports-ports/
sudo /opt/local/bin/portindex -o $SCRIPTPATH/
cd $SCRIPTPATH
#/usr/bin/curl -fsSLo PortIndex "https://ftp.fau.de/macports/release/ports/PortIndex_darwin_20_i386/PortIndex"

#sudo tar -C /opt/mports/macports-ports/ -czvf  PortIndex.tgz PortIndex PortIndex.quick
tar -czvf PortIndex.tgz /opt/mports/macports-ports/PortIndex /opt/mports/macports-ports/PortIndex.quick
exit 0